### ISSUE TITLE
How to use redpill.ko

### ISSUE THREAD

**Issue by unknown-o** [RedPill-TTG/redpill-lkm#1]
I downloaded this file（https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/x64-source/linux-3.10.x.txz/download） and compiled it according to the way in readme.md. And added the compiled file to extra.lzma. But still unable to start 6.2.4

**Comment by ttg-public** [comment]
I think with the release of https://github.com/RedPill-TTG/redpill-load this shouldn't be a problem anymore. Please reopen this issue if you're still having a problem with using it.
