### ISSUE TITLE
Add SATA DOM emulation

### ISSUE THREAD

**Issue by ttg-public** [RedPill-TTG/redpill-lkm#12]
VMWare products (ESXi, Fusion, Workstation) cannot boot from USB easily and do not support creation of virtual USB drives like proxmox does. The kernel has a way to boot from what's called "SATA DOM" (in short a dedicated small SATA device). It should be supported by the loader.

**Comment by ttg-public** [comment]
It is implemented in https://github.com/RedPill-TTG/redpill-lkm/commit/835e1fb4fae7c732b26a6e6c121bd14a6749e9eb now :)

**Comment by dperez-sct** [comment]
I see that DS918+ not support SATA DOM. It means that we cannot use redpill with esxi on 918+?

Thanks!
