### ISSUE TITLE
struct MfgCompatHddLedStatus

### ISSUE THREAD

**Issue by jumkey** [RedPill-TTG/redpill-lkm#18]
Error when I compile with DS920+ toolkit
Is this a spelling mistake?

https://github.com/RedPill-TTG/redpill-lkm/blob/23578eb2a80a66ab961b56c808c6b176b04d78ed/shim/bios/mfgbios_types.h#L179
enum MfgCompatHddLedStatus->struct MfgCompatHddLedStatus

**Comment by ttg-public** [comment]
Yes, you're right - good catch! Thank you!

Fixed in https://github.com/RedPill-TTG/redpill-lkm/commit/f3fcc22e6a79ee3463c6e9bb393dc7a8f525aab4
