### ISSUE TITLE
can we create a discuss place？

### ISSUE THREAD

**Issue by dogodefi** [RedPill-TTG/redpill-lkm#2]
like telegram，discord or else？？

**Comment by ttg-public** [comment]
Most of the discussion takes place in this thread: https://xpenology.com/forum/topic/45795-redpill-the-new-loader-for-624-discussion We also saw that the community created a telegram group.
As for reporting bugs we will prefer if they're reported in GH issues as this is the easiest way to categorize and track problems.

If you have additional questions regarding this please reopen the issue :)
