### ISSUE TITLE
Can you add boot parameter for debug?

### ISSUE THREAD

**Issue by dateno1** [RedPill-TTG/redpill-lkm#22]
Please add it for machine without serial port.

Just print out message on screen (not tty)

If someone use Low-end board (like GA-H110M-DS2V) or mini PC or Laptop they can't add serial port on board

Also recently released system board hasn't serial port (has serial head but optional part needs) (or hasn't any port or head)

**Comment by WiteWulf** [comment]
The Synology kernel has no video/framebuffer drivers in it, this is why there’s no screen output once the kernel is loaded. Console logging can only be done to a serial port (virtual or hardware).

**Comment by dateno1** [comment]
> 
> 
> The Synology kernel has no video/framebuffer drivers in it, this is why there’s no screen output once the kernel is loaded. Console logging can only be done to a serial port (virtual or hardware).

OK thanks for reply
