### ISSUE TITLE
uart_fixer.c -> ../../config/runtime_config.h not found

### ISSUE THREAD

**Issue by dodo-dk** [RedPill-TTG/redpill-lkm#9]
Hi, when i build the redpill.ko it comes a fatal error:

` CC [M]  /home/dodo/redpill-lkm/shim/uart_fixer.o
/home/dodo/redpill-lkm/shim/uart_fixer.c:3:53: fatal error: ../../config/runtime_config.h: Datei oder Verzeichnis nicht gefunden`

If i edit the redpill-lkm/shim/uart_fixer.c and change from ../../ to ../ it works.
Is this a bug or what i do wrong?

Thank you very much, Good Work!

**Comment by ttg-public** [comment]
It is a bug indeed. We hit some happy patch with folder structure probably and that's why it did work on our test VM ;)

Also reported in  https://github.com/RedPill-TTG/redpill-lkm/commit/c390f74e48bbe87ecc7ff898402cd87dc4d62f38#comments - we will push the fix quickly.

**Comment by ttg-public** [comment]
Fixed in https://github.com/RedPill-TTG/redpill-lkm/commit/163a4450b81fc13eb8064cfc1dbcefbaf5deb185
